### ISSUE TITLE
Arayüz için framework seçimi 

### ISSUE THREAD

**Issue by miratcan** [linkfloyd/linkfloyd-php#10]
Arayüz için sayfalarca CSS yazmamızı engelleyecek bir framework seçmemiz gerekiyor. Benim önerim [Kube4](https://imperavi.com/kube/) basitlik konusunda daha iyisini görmedim. Önerilere göre bir karar verelim.

**Comment by shibby** [comment]
Bootstrap <3

**Comment by aligundogdu** [comment]
1. Tercihim olmaması yönünde, 
2. Tercihim bootstrap.

**Comment by miratcan** [comment]
:( tamam

**Comment by miratcan** [comment]
Framework kullanmıyoruz konu kapandı.
