### ISSUE TITLE
Tasarım rehberinin çıkarılması.

### ISSUE THREAD

**Issue by miratcan** [linkfloyd/linkfloyd-php#11]
Şuradaki görseli temel alarak bir tasarım rehberinin ve renk paletinin çıkarılması gerekiyor:

https://dribbble.com/shots/2528706-Prdcthnt-Rddt/attachments/499120

Bu rehberi Wiki'ye ekleyeceğiz.

**Comment by miratcan** [comment]
https://github.com/linkfloyd/linkfloyd-php/wiki/Tasar%C4%B1m-Rehberi Rehber burada font boyutları eksik sadece.

**Comment by aligundogdu** [comment]
@miratcan 

> Köşeler:
> Yuvarlatılmış olarak işaretlenen köşelerin çapı 3px olarak belirlenir.

Hangi nesnelerin köşesi olacak ?  Tüm nesnelerin diyebilirsin bende butondan navbara her şeye 3px veririm.

> Tam ve yarım olarak isimlendirdiğim iki boşluk tipi tespit ettim.
> big: 20px
> normal: 15px
> half: 10px

Bu boşluklar padding mi margin mi ?

Nesneler içi padding ise, nesneler arası marginleri de belirtir misin ?

**Comment by miratcan** [comment]
Abi referansın yine o resmin kendisi. Eğer tasarımda bir yerde eğer yuvarlatılmış köşe görürsen 3px idir çapı. Ya da işte genişçe bir boşluk görürsen 20px'dir diye söyledim. Less kullanırken yukarda belirttiğim değişkenleri set edersen onları verip verip geçebilirsin.
