### ISSUE TITLE
Sistemin Less kullanmaya hazır hale getirilmesi.

### ISSUE THREAD

**Issue by miratcan** [linkfloyd/linkfloyd-php#15]
Django'da compressor adında bir modül vardı bu modül less dosyalarını compile edip html'in içerisinde css olarak gösteriyordu. Bu altyapı hazırlığının symfony için de yapılması gerekiyordur sanıyorum.

**Comment by aligundogdu** [comment]
@miratcan  abi less'i bizim ideler derliyor, ayrıca gulp da bu iş için biçilmiş kaftan o yüzden less ve css derlenmiş halde gelecek ekstra bir işe gerek yok.

**Comment by miratcan** [comment]
@aligundogdu compile edilmiş bir dosya repoda bulunmamalı diye düşünüyorum ne dersin? gulp için eklenmesi gereken bir json dosyası vardı sanırım.

**Comment by aligundogdu** [comment]
@shibby  sen nediyon ?

**Comment by miratcan** [comment]
tamam işi kapattım, ideler yapsın işi repoda tutalım

**Comment by shibby** [comment]
@miratcan @aligundogdu bunu şimdi gördüm. bildirim gelmemiş :/
teknik olarak mirat'ın söylediği doğru. derlenmiş dosya repoda bulunmamalı. her build için ayrı derleme yapılmalı. örneğin localde farklı derlenir, productionda farklı derlenir, stage de farklı derlenir.

fakat bir süre için derlenen kodu repoya atalım. sunucuda derlemek için yapılacak çalışma bizim için ekstra zaman maliyeti demek. en azından belli bir seviyeye gelene kadar derleme işini locale bırakalım. daha sonra sunucu tarafında da otomatize ederiz ve güzel bir sistem kurarız.

**Comment by miratcan** [comment]
Bu işi ilerde açmak üzere kapatıyorum.
