### ISSUE TITLE
Bağlantı başlıkları için karakter limiti 300 yapılacak.

### ISSUE THREAD

**Issue by miratcan** [linkfloyd/linkfloyd-php#23]

**Comment by miratcan** [comment]
350 karakter koyabildim?

**Comment by shibby** [comment]
evet. 300 konusunda hem fikiriz. 350 yapmamım sebebine gelince, ben #müzik #php vs gibi etiketler eklemek istiyorum. şu an etiket sistemimiz yok ve bu koyduğum etiketler sistemsel olarak çalışır değil. ama benim en azından kendim için sınıflandırma yapmaya ihtiyacım var. 50 karakter goes to etikets.

**Comment by miratcan** [comment]
e peki etiket sistemi geldiğinde ne olacak? hastag kısımlarını silecek miyiz başlıklardan?

**Comment by shibby** [comment]
sileriz. çok problem değil. tek seferlik migration tool yazarız.

**Comment by miratcan** [comment]
okeydir, zaten şimdi model belli değil twitter'daki gibi etiketler title'a dahil mi olacak yoksa tumblr'ın yaptığı gibi ayrı bir form fieldında etiket mi yazacağız belli değil bir ara karar veririz ona hep birlikte.
