### ISSUE TITLE
Gönderi düzenleme.

### ISSUE THREAD

**Issue by miratcan** [linkfloyd/linkfloyd-php#27]
Kullanıcılar bütün gönderi listeleme sayfalarında kendilerine ait gönderilerin altında bir "düzenle" bağlantısı görecekler. Bu bağlantıya tıklandığında gönderinin sadece başlığını düzenleyebildiğimiz bir ekrana gideceğiz. Burada düzenlemeyi yapıp kaydettiğimizde gelinen sayfaya geri dönmemiz gerekmekte. (Gelinen sayfayı URL üzerinden geçirebiliriz örneğin /link/edit/123/?return=/profile/ gibi.)

NOT: API karşılığının da yazılması gerekiyor.

**Comment by shibby** [comment]
@miratcan URL üzerinden geri döndürmek çok fazla tercih edilen bir yöntem değil sanırsam. Bu konuda daha önce baya ciddi açıklar olabileceğini görmüştüm. Fakat şu an hatırlamıyorum. Güvenlik açısından bu konuyu öğrenmek lazım. Sırf bu issue özelinde değil, genel olarak faydalı olacaktır. 
Symfony'de bu konu hakkındaki sorularda genellik REFERRER bilgisini almaları söylenmiş. Referer'den almakla url'den almak arasında bir fark göremiyorum. 
Dediğim gibi bu konuya güvenlik açısından bir bakmak lazım. 

Düzenlemede sadece title düzenlenecek. Zaten sadece title mevcut. İleride tag/konu düzenleme yaparız. 

Son olarak, yapılan değişiklikleri history olarak kaydetmek istiyorum. Bunu da bu işle birlikte yapmak istiyorum. Tek sıkıntı veritabanı tasarımı. Bir de gönderinin editlendiğine dair bir mark lazım. (updated_at kolonu var, ama updated_at kolonunun created_at kolonundan farklı olması kullanıcının illa gönderisinde değişiklik yapığı anlamına gelmez.)

**Comment by miratcan** [comment]
> @miratcan URL üzerinden geri döndürmek çok fazla tercih edilen bir yöntem değil sanırsam. Bu konuda daha önce baya ciddi açıklar olabileceğini görmüştüm. Fakat şu an hatırlamıyorum. Güvenlik açısından bu konuyu öğrenmek lazım. Sırf bu issue özelinde değil, genel olarak faydalı olacaktır. 
> Symfony'de bu konu hakkındaki sorularda genellik REFERRER bilgisini almaları söylenmiş. Referer'den almakla url'den almak arasında bir fark göremiyorum. 

Tamamdır bana uyar, bu redirect etme sırasında GET metodu kullanılacağı için sorun olmayacağını düşünüyorum. Prensip olarak GET ile çağırılan hiç bir URL sistem üzerinde değişiklik yapamamalı.

> Düzenlemede sadece title düzenlenecek. Zaten sadece title mevcut. İleride tag/konu düzenleme yaparız.

Aynen bu ilerdeki iş.

> Son olarak, yapılan değişiklikleri history olarak kaydetmek istiyorum. Bunu da bu işle birlikte yapmak istiyorum. Tek sıkıntı veritabanı tasarımı. Bir de gönderinin editlendiğine dair bir mark lazım. (updated_at kolonu var, ama updated_at kolonunun created_at kolonundan farklı olması kullanıcının illa gönderisinde değişiklik yapığı anlamına gelmez.)

Eğer ilerde bunun veritabanı değişikliğini yapmak çok zor olmayacaksa şimdilik girme buna. Daha history'ye ihtiyacımız var mı yok mu onu bilmiyoruz. Benim yok ihtiyacım kimin var? İlerde yapalım bunu.
