### ISSUE TITLE
Master dalının güncellenmesiyle otomatik gerçekleşen deployment.

### ISSUE THREAD

**Issue by miratcan** [linkfloyd/linkfloyd-php#29]
(bu deployment kelimesinin türkçesini bulamadıkça uyuz oluyorum ya bu arada)

Master dalımızı ger güncellediğimizde Github'ın çengellerini kullanarak deployment tetikleyelim. Master güncellemesi yaptığımızda linkfloyd.com da güncellensin.

**Comment by shibby** [comment]
Şu an için otomatik bir deployment olmamakla birlikte stage adresinde develop branchini baz alıyoruz. 
İlerleyen zamanda, yine otomatik bir deployment süreci olmamasından yanayım. Güncelleme için bir bash betiği yazarız ve onu kullanarak sunucuda güncelleme yaparız.
