### ISSUE TITLE
Proje ismini linkfloyd-php yerine lf2 ya da linkfloyd2 olarak değiştirelim diyorum.

### ISSUE THREAD

**Issue by miratcan** [linkfloyd/linkfloyd-php#31]
Diğer bağlantılı repoların adını da (FloydStyle hariç, onun ismi gayet iyi) linkfloyd2-blabla ya da lf2-blabla şeklinde isimlendiririz.

**Comment by aligundogdu** [comment]
Facebook, twitter , airbnb gibi firmalar organizasyonlarında oluşturduğu repolar için hep başka ve alakasız isimler seçiyor,

ben de her reponun bir kod alı ile çıkmasını öneriyorum.

**Comment by miratcan** [comment]
@aligundogdu Linkfloyd için geliştirdiğim oylama sistemi ayrı repo olarak "qhonuskan" adında duruyordu ben de seviyorum o yaklaşımı ama illa olsun diye bir kaygım da yok. Sanırım orada doğru yaklaşımın şöyle olması gerekiyor: 
- Direkt linkfloyd'un çalışması için özel olarak inşa edilmiş projeler linkfloyd-blabla ismiyle adlandırılmalı: Örneğin vagrant provisioner projesi.
- Diğer projelerde kullanılabilecek kütüphaneler özgün isimlendirilmeli. (Örneğin css framework projesi)

Reddit'in projelerine baktım bu söylediğim şekilde yapılmış isimlendirmeleri.

![ekran resmi 2016-11-17 12 35 31](https://cloud.githubusercontent.com/assets/140968/20383903/4333a260-acba-11e6-86f6-a8096fb3add2.png)

Benim asıl yapmak istediğim şu "**linkfloyd-php**" deki "_-php_" kısmını kaldırmak. lf2 ya da linkfloyd2 şeklinde yaparsak iyi olabilir.

**Comment by aligundogdu** [comment]
Anladım.

> Sanırım orada doğru yaklaşımın şöyle olması gerekiyor:

senin doğrularına uyarım, sen isimleri ver ben değiştiririm.

**Comment by miratcan** [comment]
lf2 mi linkfloyd2 mi? @shibby sen ne düşünüyorsun?

**Comment by shibby** [comment]
Linkfloyd2 dememize gerek yok. Ya da şart değil. linkfloyd-php gayet uygun. Orjinal linkfloyd projesi de bi süre sonra kendi adını linkfloyd-museum olarak değiştirebilir :)

**Comment by miratcan** [comment]
Wontfix.
