### ISSUE TITLE
iframely kütüphanesi neden klonlandı?

### ISSUE THREAD

**Issue by miratcan** [linkfloyd/linkfloyd-php#32]
Bir amacı var mı? yoksa silmek istiyorum.

**Comment by shibby** [comment]
Saygıdan ötürü.

**Comment by miratcan** [comment]
sadece saygıdan ötürüyse yok edelim abi :) wikide falan söyleriz bunu kullandık çok güzeldi diye.

**Comment by miratcan** [comment]
sildim
