### ISSUE TITLE
linkfloyd-ansible-provisioner, linfloyd-php projesiyle birleştirilebilir mi?

### ISSUE THREAD

**Issue by miratcan** [linkfloyd/linkfloyd-php#33]
Şimdi gidip /home/htdocs/ altına linkfloyd-php projesini atıyorum, sonra gidip /home/Repos/Mirat/blabla altına vagrant projesini atıyorum bu dağınıklık beni rahatsız ediyor. Linkfloyd'u geliştirecek kişilerin zaten ihtiyacı olan bir şey için iki ayrı depoya ihtiyaç duymak, iki ayrı git clone işlemi yapmak bende dağınıklık hissi yaratıyor. Ben diyorum ki bu provision işini asıl projenin içine alalım. Ne dersiniz?

**Comment by shibby** [comment]
Ansible için ayrı repo olması mantıklı. Bu ayrı bir proje. 

Buradan oluşan Vagrant box'ı (1.4 gb) yükleyip, daha sonra o box'ı kullanan bir VagrantFile ana proje altına eklenebilir. Hatta olması gereken budur.
