### ISSUE TITLE
Login ve kayıt işleri

### ISSUE THREAD

**Issue by miratcan** [linkfloyd/linkfloyd-php#4]
Şimdilik siteye sadece username ve password belirleyerek kayıt olabilelim ve bu bilgilerle giriş işlemini yapabilelim. E-posta alma ve onaylamayla sonraki dönemlerde ilgilenebiliriz.

**Comment by shibby** [comment]
şu an e-posta alıyoruz. fieldler: e-posta, nickname, parola, parola tekrar. 
ama e-posta validation yok. (ileride isteidğimiz zaman 1-2 configg ayarıyla ekleyebiliyoruz)

**Comment by miratcan** [comment]
> şu an e-posta alıyoruz. fieldler: e-posta, nickname, parola, parola tekrar.
> ama e-posta validation yok. (ileride isteidğimiz zaman 1-2 configg ayarıyla ekleyebiliyoruz)

OK bana uyar.

**Comment by miratcan** [comment]
TEST OK
