### ISSUE TITLE
Bağlantı Gönderme

### ISSUE THREAD

**Issue by miratcan** [linkfloyd/linkfloyd-php#5]
Kulanıcı giriş yaptıktan sonra bir bağlantı gönderebilmeli, bunun için bir satırlık bir başlık ve bağlantının kendisini vermesi yeterli. Başlık 255 karakterden uzun vermeyelim boku çıkmasın. Ayrıca URL yacağımız yere invalid bir URL veya ulaşılamayan bir sayfanın verilmediğinden emin olmak lazım. Bu kontrolleri backend tarafında yapalım.

Adres olarak: post/create/ kullanabiliriz.
Öte yandan API'a POST talebinde bulunarak gönderiyi diğer clientlar ile de yapabilelim. İstediği veriler: title, ve url olmalı, ayrıca authentication olmuş kullanıcı yapabiliyor olmalı bunu.

**Comment by shibby** [comment]
input alanına, url yapıştırdığında ajax ile title bilgisini alsın. (@aligundogdu vuejs yaparsın sen burda lsad)
title field'ine yazsın. (bu alan değiştirilemez mi olsun?)
eğer siteden title bilgisi gelmezse? (örneğin sadece görsel paylaşırsa)

**Comment by shibby** [comment]
input alanına, url yapıştırdığında ajax ile title bilgisini alsın. (@aligundogdu vuejs yaparsın sen burda lsad)
title field'ine yazsın. (bu alan değiştirilemez mi olsun?)
eğer siteden title bilgisi gelmezse? (örneğin sadece görsel paylaşırsa)

**Comment by shibby** [comment]
input alanına, url yapıştırdığında ajax ile title bilgisini alsın. (@aligundogdu vuejs yaparsın sen burda lsad)
title field'ine yazsın. (bu alan değiştirilemez mi olsun?)
eğer siteden title bilgisi gelmezse? (örneğin sadece görsel paylaşırsa)

**Comment by miratcan** [comment]
>  eğer siteden title bilgisi gelmezse? (örneğin sadece görsel paylaşırsa)

Abi siteden title getirmeyi falan bırak şimdilik, gönderi yapan kişi yazsın başlık. LF1'de o otomatik title doldurma işi yüzünden sanki bütün içeriği botlarla oluşturuyormuşum gibi bir izlenim olmuştu.

**Comment by miratcan** [comment]
>  eğer siteden title bilgisi gelmezse? (örneğin sadece görsel paylaşırsa)

Abi siteden title getirmeyi falan bırak şimdilik, gönderi yapan kişi yazsın başlık. LF1'de o otomatik title doldurma işi yüzünden sanki bütün içeriği botlarla oluşturuyormuşum gibi bir izlenim olmuştu.

**Comment by miratcan** [comment]
>  eğer siteden title bilgisi gelmezse? (örneğin sadece görsel paylaşırsa)

Abi siteden title getirmeyi falan bırak şimdilik, gönderi yapan kişi yazsın başlık. LF1'de o otomatik title doldurma işi yüzünden sanki bütün içeriği botlarla oluşturuyormuşum gibi bir izlenim olmuştu.

**Comment by miratcan** [comment]
>  eğer siteden title bilgisi gelmezse? (örneğin sadece görsel paylaşırsa)

Abi siteden title getirmeyi falan bırak şimdilik, gönderi yapan kişi yazsın başlık. LF1'de o otomatik title doldurma işi yüzünden sanki bütün içeriği botlarla oluşturuyormuşum gibi bir izlenim olmuştu.

**Comment by miratcan** [comment]
>  eğer siteden title bilgisi gelmezse? (örneğin sadece görsel paylaşırsa)

Abi siteden title getirmeyi falan bırak şimdilik, gönderi yapan kişi yazsın başlık. LF1'de o otomatik title doldurma işi yüzünden sanki bütün içeriği botlarla oluşturuyormuşum gibi bir izlenim olmuştu.

**Comment by miratcan** [comment]
>  eğer siteden title bilgisi gelmezse? (örneğin sadece görsel paylaşırsa)

Abi siteden title getirmeyi falan bırak şimdilik, gönderi yapan kişi yazsın başlık. LF1'de o otomatik title doldurma işi yüzünden sanki bütün içeriği botlarla oluşturuyormuşum gibi bir izlenim olmuştu.

**Comment by miratcan** [comment]
>  eğer siteden title bilgisi gelmezse? (örneğin sadece görsel paylaşırsa)

Abi siteden title getirmeyi falan bırak şimdilik, gönderi yapan kişi yazsın başlık. LF1'de o otomatik title doldurma işi yüzünden sanki bütün içeriği botlarla oluşturuyormuşum gibi bir izlenim olmuştu.

**Comment by shibby** [comment]
title field'ini arkaplanda kayıt yaparken alacağım o zaman. kullanıcı sadece description girebilsin. benim istediğim şey de buydu zaten. kullanıcılar paylaştıkları şeylerle ilgili kendi görüşlerini yazsın. 

kayıt işlemini direkt ajax yapabiliriz ama. ajax-first yazarsak api direkt hazır olmuş olur.

**Comment by miratcan** [comment]
> title field'ini arkaplanda kayıt yaparken alacağım o zaman. kullanıcı sadece description girebilsin. benim istediğim şey de buydu zaten. kullanıcılar paylaştıkları şeylerle ilgili kendi görüşlerini yazsın. 

Abi bence post_detail diye ayrı bir tablo açar, orada post ile ilgili preview oluşturmak için gerekli veri toplama işini yaparız ilerde. title, description, preview_image gibi alanlar olur orada. O yüzden şimdilik karıştırmayalım derim ben.

> kayıt işlemini direkt ajax yapabiliriz ama. ajax-first yazarsak api direkt hazır olmuş olur. 

:+1:

**Comment by shibby** [comment]
> Abi bence post_detail diye ayrı bir tablo açar, orada post ile ilgili preview oluşturmak için gerekli veri toplama işini yaparız ilerde. title, description, preview_image gibi alanlar olur orada. O yüzden şimdilik karıştırmayalım derim ben.

evet dediğin gibi. links diye bir tablo oluşturdum. url, title, description, media 
bu alanlar direkt siteden gelen alanlar.

**Comment by miratcan** [comment]
> evet dediğin gibi. links diye bir tablo oluşturdum. url, title, description, media
> bu alanlar direkt siteden gelen alanlar.

LF1'de bazı şeyleri ön göremeyip tablo yapılarını düzgün oluşturamamıştım. Şu anki model yapısını görebileceğim bir şey var mı? Ben de baksam iyi olacak.

**Comment by miratcan** [comment]
TEST OK
