### ISSUE TITLE
Gönderiler için önizleme resmi oluşturma.

### ISSUE THREAD

**Issue by miratcan** [linkfloyd/linkfloyd-php#9]
Gönderi yapıldığı zaman bir ayrı worker içerisinde bu link hakkında bilgi toplama işini yapalım. Şimdilik sadece preview imajını alsın. İlk olarak og:image etiketinden almayı deneyelim, bulamazsak ref'i image olan link etiketinden, orada da bulamazsak sayfadaki içeriğindeki ilk büyük imajı alalım. 

Sayfayı yenilediğimde eğer bilgi toplama işi bittiyse önizleme resmi ile, bitmediyse resim olmadan gönderiyi görelim.

**Comment by shibby** [comment]
şu anda iframe.ly api'larını kullanıyoruz görseli çekmek için.

**Comment by miratcan** [comment]
> şu anda iframe.ly api'larını kullanıyoruz görseli çekmek için.

E buradan ne anlamalıyım? İşi kapat mı diyorsun?

**Comment by shibby** [comment]
Şu an basit seviyede iş görüyor. Örneğin, og:image bulamadığı durumda ne yapıyor bilmiyoruz. Resimsiz blog yazısında ne getiriyor bilmiyoruz. Biraz kullandıktan sonra eksikleri çıkar ve ona göre güncelleme yaparız.

O yüzden iş durabilir.

**Comment by miratcan** [comment]
@shibby tamam şimdilik işi kapatıyorum, öte yandan ben bunu bir mikroservis olarak yazabilirim de. API yerine onu kullanırsın.

**Comment by shibby** [comment]
@miratcan bu konuda kullandığım api 1-2 aşamada eksiği var. 
#34 numaralı issue'deki problemi doğrudan iframe.ly ile aşamıyorum. 
Benzer şekilde, sadece bir görsel paylaştığımızda (`domain.com/bilmemne.jpg`) sistem bunda doğal olarak thumbnail_url bulamıyor. 

bu yüzden bir microservis çok işimize yarayacaktır. `parser.linkfloyd.com`
1- iframe.ly api üzerinden veriyi çeker.
2- a) gerekli bilgiler bulunamazsa, senin microservisin bulmaya çalışır. 
2- b) #34 teki gibi hatalı url leri tespit eder ve çözer.
3- belirlediğimiz bir formatta dönüş yapar.
